spring:
    application:
      name: userService

server:
  port: 9001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:
    com.netflix.discovery: DEBUG
    com.netflix.discovery.shared.transport: DEBUG