spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file://C:\Users\zhfld\OneDrive\바탕 화면\develop\IntelliJSpace\ecommerce-config

server:
  port: 8888
